name: Test MacOs

on:
  workflow_dispatch:

jobs:
  testing-job:
    runs-on: macos-10.15
    steps:
      - name: Background process
        run: |
          brew install coreutils
          while true; do echo AAAAAAAAAAAA; date; vm_stat; iostat; df -h; sleep 2; done &  echo 123123123123
