name: Test MacOs

on:
  workflow_dispatch:

jobs:
  testing-job:
    runs-on: macos-10.15
    steps:
      - name: Redirect output to stderr
        run: |
          echo "This is the output!" 1>&2
      - name: Background process
        run: |
          brew install coreutils
          while true; do echo AAAAAAAAAAAA; date; vm_stat; iostat; df -h; sleep 3; done
