name: Test shell

on:
  workflow_dispatch:

jobs:
  test_shell:
    runs-on: ubuntu-latest
    steps:
      - name: Print link to current workflow
        run: |
          echo "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" 
      - name: Logging to stdout and stderr
        run: |
          printf "Output 1!\n" &&
          printf "\n\n\nOutput 2!\n" 1>&2 &&
          printf "\n\n\nOutput 3!\n" &&
          printf "\n\n\nOutput 4!\n" 1>&2
          
      - name: Logging to stderr
        run: |
          printf "Output 1!\n" 1>&2 &&
          printf "\n\n\nOutput 2!\n" 1>&2 &&
          printf "\n\n\nOutput 3!\n" 1>&2 &&
          printf "\n\n\nOutput 4!\n" 1>&2
