---
name: "Test mounting"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
env:
  BAZEL_BASE_IMAGE: "ghcr.io/magma/magma/bazel-base:latest"

jobs:
  mounting_test:
    name: Test mounting
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        # This is necessary for overlays into the Docker container below.
        uses: actions/checkout@v2
      - name: Setup Bazel Base Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          options: --pull always
          # Run a simple echo command to pull down the image. This makes it a bit more clear how much time is spent on building Magma and not pulling down the image.
          run: |
            echo "Pulled the bazel base image!"
      - name: Bazel build
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v /tmp/bazel:/tmp/bazel  -v ${{ github.workspace }}:/workspaces
          run: |
            pwd
            ls
            cd workspaces
            pwd
            bazel build //main:hello-world
      - name: Bazel build again
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v /tmp/bazel:/tmp/bazel
          run: |
            bazel build //main:hello-world
            
