name: LTE integ test

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: 'CPU allocated to the VM'
        default: 2
        required: true
        type: number
      RAM:
        description: 'RAM allocated to the VM'
        default: 8192
        required: true
        type: number

jobs:
  lte-integ-test:
    runs-on: macos-10.15
    steps:
      - name: Test inputs
        run: |
          echo "VM Resources: CPU: ${{ github.event.inputs.CPU }} RAM: ${{ github.event.inputs.RAM }}"
          export MAGMA_DEV_CPUS=${{ github.event.inputs.CPU }}
          export MAGMA_DEV_MEMORY_MB=${{ github.event.inputs.RAM }}
