name: Test workflow trigger

on:
  push:
    branches:
      - main
      - 'v1.*'

jobs:
  path_filter:
    if: github.repository_owner == 'not-LKreutzer'
    runs-on: ubuntu-latest
    steps:
      # Need to get git on push event
      - name: Path filter step
        run: |
          echo "The path filter ran!"

  testing_the_trigger:
    runs-on: ubuntu-latest
    needs:
      - path_filter
    steps:
      - name: Test
        run: |
          echo "The Testing-the-trigger job ran!"
