name: Test workflow trigger

on:
  push:
    branches:
      - master
      - 'v1.*'

jobs:
  Testing-the-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "It ran!"
