name: Test if conditions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  path_filter:
    runs-on: ubuntu-latest
    steps:
      # Need to get git on push event
      - name: Path filter step
        run: |
          echo "The path filter ran!"
      - name: This is the if step
        if: |
          github.repository_owner == 'LKreutzer' &&
          github.ref_name == 'main'
        run: |
          echo "This is the branch LKreutzer/GH-actions-testing/main!"

          
  job_with_failing_step:
    runs-on: ubuntu-latest
    needs:
      - path_filter
    steps:
      - name: Logging
        run: |
          echo "This is job_with_failing_step:"
      - name: Failure
        run: |
          exit 1
      - name: Step without always()
        if: github.repository_owner == 'LKreutzer' && github.ref_name == 'main'
        run: |
          echo "You should not see this!"
          
  job_with_failing_step_and_always:
    runs-on: ubuntu-latest
    needs:
      - path_filter
    steps:
      - name: Logging
        run: |
          echo "This is the job_with_failing_step_and_always:"
      - name: Failure
        run: |
          exit 1
      - name: Step with always()
        if: always() && github.repository_owner == 'LKreutzer' && github.ref_name == 'main'
        run: |
          echo "If you can see this then the always() works!"

  job_with_braces:
    runs-on: ubuntu-latest
    needs:
      - path_filter
    steps:
      - name: Logging
        run: |
          echo "This is job_with_braces:"
      - name: Failure
        run: |
          exit 1
      - name: Step with always()
        if: ${{ always() && github.repository_owner == 'LKreutzer' && github.ref_name == 'main' }}
        run: |
          echo "If you can see this then the always() works!"

